/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static java.lang.Boolean.TRUE;

/**
 *
 * @author lidia
 */
public class TelaPrincipalSDI extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalSDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneTelaPrincipal = new javax.swing.JDesktopPane();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemCadastrarUsuario = new javax.swing.JMenuItem();
        jMenuItemAlterarUsuario = new javax.swing.JMenuItem();
        jMenuItemExcluirUsuario = new javax.swing.JMenuItem();
        jMenuItemPesquisarUsuario = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemCadastrarCliente = new javax.swing.JMenuItem();
        jMenuItemAlterarCliente = new javax.swing.JMenuItem();
        jMenuItemExcluirCliente = new javax.swing.JMenuItem();
        jMenuItemPesquisarCliente = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA AAAAAAA");

        javax.swing.GroupLayout jDesktopPaneTelaPrincipalLayout = new javax.swing.GroupLayout(jDesktopPaneTelaPrincipal);
        jDesktopPaneTelaPrincipal.setLayout(jDesktopPaneTelaPrincipalLayout);
        jDesktopPaneTelaPrincipalLayout.setHorizontalGroup(
            jDesktopPaneTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jDesktopPaneTelaPrincipalLayout.setVerticalGroup(
            jDesktopPaneTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );

        jMenuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-text.png"))); // NOI18N
        jMenuArquivo.setText("Arquivo");
        jMenuArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoActionPerformed(evt);
            }
        });

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuArquivo.add(jMenuItemSair);

        jMenuBarPrincipal.add(jMenuArquivo);

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jMenuUsuario.setText("Usuários");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });

        jMenuItemCadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-plus.png"))); // NOI18N
        jMenuItemCadastrarUsuario.setText("Cadastrar");
        jMenuItemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemCadastrarUsuario);

        jMenuItemAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jMenuItemAlterarUsuario.setText("Alterar");
        jMenuItemAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemAlterarUsuario);

        jMenuItemExcluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-square.png"))); // NOI18N
        jMenuItemExcluirUsuario.setText("Excluir");
        jMenuItemExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemExcluirUsuario);

        jMenuItemPesquisarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jMenuItemPesquisarUsuario.setText("Pesquisar");
        jMenuUsuario.add(jMenuItemPesquisarUsuario);

        jMenuBarPrincipal.add(jMenuUsuario);

        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        jMenuCliente.setText("Clientes");

        jMenuItemCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-plus.png"))); // NOI18N
        jMenuItemCadastrarCliente.setText("Cadastrar");
        jMenuCliente.add(jMenuItemCadastrarCliente);

        jMenuItemAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jMenuItemAlterarCliente.setText("Alterar");
        jMenuItemAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemAlterarCliente);

        jMenuItemExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-square.png"))); // NOI18N
        jMenuItemExcluirCliente.setText("Excluir");
        jMenuCliente.add(jMenuItemExcluirCliente);

        jMenuItemPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jMenuItemPesquisarCliente.setText("Pesquisar");
        jMenuCliente.add(jMenuItemPesquisarCliente);

        jMenuBarPrincipal.add(jMenuCliente);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/codepen.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuBarPrincipal.add(jMenuSobre);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneTelaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneTelaPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAlterarUsuarioActionPerformed

    private void jMenuItemExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemExcluirUsuarioActionPerformed

    private void jMenuItemAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAlterarClienteActionPerformed

    private void jMenuItemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        new TelaCadastroUsuarioSDI().setVisible(TRUE);
    }//GEN-LAST:event_jMenuItemCadastrarUsuarioActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalSDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneTelaPrincipal;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemAlterarCliente;
    private javax.swing.JMenuItem jMenuItemAlterarUsuario;
    private javax.swing.JMenuItem jMenuItemCadastrarCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarUsuario;
    private javax.swing.JMenuItem jMenuItemExcluirCliente;
    private javax.swing.JMenuItem jMenuItemExcluirUsuario;
    private javax.swing.JMenuItem jMenuItemPesquisarCliente;
    private javax.swing.JMenuItem jMenuItemPesquisarUsuario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenu jMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
